### ISSUE TITLE
Cant paste into the input box :-(

### ISSUE THREAD

**Issue by JakeChampion** [seanmtracey/Carpathia#1]
Just tried to use this app to backup some vines but couldn't paste into the input box. I'm on a Macbook and tried using `cmd + v` which didn't work. I then tried to right-click the input box but no menu came up.

How do I put my profile url into the box?

**Comment by seanmtracey** [comment]
That's odd. I can paste into the box. What version of OS X are you running?

**Comment by seanmtracey** [comment]
Ah, turns out I need to specify the keyboard bindings I want Electron to have. Have added to 0.3.0 and will release shortly.

**Comment by JakeChampion** [comment]
Testing now.

**Comment by JakeChampion** [comment]
`cmd+v` works, right-clicking still does not work. Ooh, it now has an edit menu in the system bar at the top!
